const countries = {
    "ar-SA": "Arabic",
    "bn-IN": "Bengali",
    "de-DE": "German",
    "el-GR": "Greek",
    "en-GB": "English",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "hi-IN": "Hindi",
    "id-ID": "Indonesian",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "ur-PK": "Urdu",
    "ru-RU": "Russian",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
    "tr-TR": "Turkish",
}